[tool.poetry]
name = "tap-coda"
version = "0.0.1"
description = "`tap-coda` is a Singer tap for Coda, built with the Meltano SDK for Singer Taps."
authors = ["Edgar Ramírez-Mondragón <edgarrm358@gmail.com>"]
keywords = [
    "ELT",
    "Coda",
]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "<3.12,>=3.7.1"
singer-sdk = "==0.22.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
src_paths = "tap_coda"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-coda = 'tap_coda.tap:TapCoda.cli'
