[tool.poetry]
name = "tap-coda"
version = "0.0.1"
description = "`tap-coda` is a Singer tap for Coda, built with the Meltano SDK for Singer Taps."
authors = ["Edgar Ramírez-Mondragón <edgarrm358@gmail.com>"]
keywords = [
    "ELT",
    "Coda",
]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "<3.11,>=3.7.1"
singer-sdk = "==0.4.4"
toolz = "==0.11.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.0"
tox = "^3.24.5"
flake8 = "^4.0.1"
black = "^22.1"
pydocstyle = "^6.1.1"
mypy = "^0.931"
types-requests = "^2.27.12"
isort = "^5.10.1"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
src_paths = "tap_coda"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-coda = 'tap_coda.tap:TapCoda.cli'
